# Generated by Django 5.2.2 on 2025-08-29 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Опубликовано'), ('draft', 'Неопубликовано')], default='draft', verbose_name='Статус'),
        ),
    ]
