# Generated by Django 5.2.2 on 2025-09-20 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
