# Generated by Django 5.2.2 on 2025-10-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_comment_is_edited_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='level',
            field=models.PositiveIntegerField(default=0, verbose_name='Уровень вложенности'),
        ),
    ]
